import type { Metadata } from "next";
import GuideLayout from "@/components/layout/GuideLayout";
import Callout from "@/components/ui/Callout";

export const metadata: Metadata = {
  title: "AI 3D Animation Guide — Create 3D Characters & Scenes",
  description:
    "How to create 3D-style AI characters, scenes, and animated videos without any 3D software. A beginner's step-by-step guide.",
  alternates: { canonical: "/learn/3d-animation-guide" },
};

export default function ThreeDAnimationGuidePage() {
  return (
    <GuideLayout
      crumbs={[
        { label: "Home", href: "/" },
        { label: "Learn", href: "/start-here" },
        { label: "3D Animation Guide" },
      ]}
      title="AI 3D Animation Guide"
      subtitle="How to create 3D-style characters, scenes, and animated clips using AI tools — no 3D software, no rigging, no technical experience required."
      readTime="~45 min"
      outcomes={[
        "Generate a consistent AI character in a 3D-style",
        "Create your first AI-animated clip from a still image",
        "Understand character consistency and how to maintain it",
        "Know which tools to use for each step",
      ]}
      prevGuide={{ label: "AI Animation Basics", href: "/learn/ai-animation-basics" }}
      nextGuide={{ label: "Cartoon Creation Guide", href: "/learn/cartoon-creation-guide" }}
      relatedGuides={[
        { label: "Tools Directory", href: "/tools" },
        { label: "Workflow Explainer", href: "/workflow" },
        { label: "Case Studies", href: "/case-studies" },
      ]}
    >
      <h2>What does &quot;3D-style AI animation&quot; mean?</h2>
      <p>
        When we say &quot;3D-style&quot; in the context of AI animation, we mean visuals
        that <em>look</em> three-dimensional — with depth, lighting, shadows, and texture —
        but are generated by AI rather than built in 3D software like Blender or Maya.
      </p>
      <p>
        The result is visually indistinguishable from real 3D animation at first glance,
        but the process is massively simpler. You describe what you want, and the AI
        generates a polished 3D-style render.
      </p>

      <Callout type="tip" title="Key insight">
        You don&apos;t need to &quot;model&quot; anything. There are no vertices, no rigs,
        no UV maps. You describe, the AI renders.
      </Callout>

      <h2>Step 1 — Design your character concept</h2>
      <p>
        Before generating anything, decide on the core traits of your character:
      </p>
      <ul>
        <li><strong>Visual style</strong> — Pixar-style 3D? Anime? Realistic? Cartoon?</li>
        <li><strong>Key features</strong> — what makes this character recognizable? (big eyes, red shoes, a specific hairstyle)</li>
        <li><strong>Personality</strong> — happy, mischievous, heroic? This affects expression and pose</li>
        <li><strong>Setting</strong> — what world does this character live in?</li>
      </ul>
      <p>
        Write this down in plain language. This becomes the seed for your image prompts.
      </p>

      <h2>Step 2 — Generate your character with image AI</h2>
      <p>
        Use an image AI tool (we recommend starting with Midjourney or DALL-E 3) with
        a detailed, structured prompt. Here&apos;s a proven prompt formula:
      </p>
      <blockquote>
        [Style] [Character description] [Pose] [Background] [Lighting] [Camera angle]
      </blockquote>
      <p>Example:</p>
      <blockquote>
        Pixar 3D animation style, cute baby character with big brown eyes and a football
        jersey, laughing pose with arms raised, glowing stadium background, dramatic
        rim lighting, front-facing medium shot, octane render, cinematic quality
      </blockquote>
      <p>
        Generate several variations and choose the one that best captures your vision.
        This is your &quot;reference image&quot; — the foundation for character consistency.
      </p>

      <Callout type="info" title="Character consistency">
        Character consistency means your character looks the same across multiple
        images and video clips. The key is to save your exact prompt (including any
        style seeds or model settings) and reuse it with slight modifications for
        different poses and expressions.
      </Callout>

      <h2>Step 3 — Create character variations</h2>
      <p>
        Once you have your base character, generate variations:
      </p>
      <ul>
        <li>Different expressions (happy, surprised, determined, sad)</li>
        <li>Different poses (running, jumping, sitting, pointing)</li>
        <li>Different angles (front, side, three-quarter)</li>
        <li>Different scenes (indoor, outdoor, night, day)</li>
      </ul>
      <p>
        Keep your character description identical across all prompts — only change the
        pose, expression, or background. This maintains consistency.
      </p>

      <h2>Step 4 — Animate your character (Image to Video)</h2>
      <p>
        Take your best still image and bring it to life using a video AI tool. Good
        options include Runway Gen-3, Kling AI, or Pika Labs.
      </p>
      <p>
        The process is simple:
      </p>
      <ol>
        <li>Upload your AI-generated image to the video tool</li>
        <li>Write a short motion prompt (e.g., &quot;character laughs and jumps with excitement, camera pulls back slightly&quot;)</li>
        <li>Generate the video clip (typically 4–8 seconds)</li>
        <li>Review and regenerate if needed</li>
      </ol>

      <Callout type="tip" title="Motion prompts that work">
        Be specific about what moves and how. &quot;Character waves hand slowly&quot; works
        better than &quot;character moves.&quot; Describe the camera too: &quot;slow zoom in&quot;,
        &quot;cinematic pan right&quot;.
      </Callout>

      <h2>Step 5 — Create a scene</h2>
      <p>
        Characters need a world. Use the same image AI tool to generate backgrounds
        and environments that match your character&apos;s style. Keep the style descriptor
        consistent (&quot;Pixar 3D animation style&quot; should appear in every prompt).
      </p>
      <p>
        You can then composite your character against these backgrounds in a video
        editor, or include the background description directly in your character prompt.
      </p>

      <h2>A real example workflow</h2>
      <p>
        Here&apos;s exactly how a simple 3D AI animation is made in one session:
      </p>
      <ol>
        <li>Decide on character and story (10 mins)</li>
        <li>Generate 10–20 character image variations, pick the best (20 mins)</li>
        <li>Generate 5–10 scene/background images (15 mins)</li>
        <li>Animate 3–5 key clips using video AI (30 mins)</li>
        <li>Add voiceover with voice AI (10 mins)</li>
        <li>Edit clips together in a simple editor (20 mins)</li>
        <li>Add music and export (10 mins)</li>
      </ol>
      <p>
        Total: about 2 hours for a polished 30–60 second AI animation. As you get
        faster, this drops to 45–60 minutes.
      </p>

      <h2>Ready for the next step</h2>
      <p>
        You now understand the full 3D AI animation pipeline. In the next guide,
        you&apos;ll learn how to apply this specifically to cartoon-style characters —
        with more personality, expressions, and narrative.
      </p>
    </GuideLayout>
  );
}
